const express =require('express')
const mongoose=require('mongoose')
const cors=require('cors')
const AuthRoute=require('./Routes/AuthRoute')
require('dotenv').config()
mongoose.connect(process.env.MONGO_URI,{ useNewUrlParser: true, useUnifiedTopology: true })
.then(()=>console.log("Database Connected"))
.catch((err)=>console.log(err))
const app=express()
app.use(cors())
app.use(express.json())
app.use('/',AuthRoute)
app.listen(process.env.PORT,()=>console.log("SERVER IS RUNNING"))
